################################################################################
# CIU-NETX User configuration file
# Options set here will override the base settings provided by config_defaults.ini
# Only a subset of all options available in config_defaults.ini is displayed here.
################################################################################


[general]
# Application instance description, displayed in the SystemTray tooltip
# [ name: description, type: string, default: Kiln 1 ]
description = Kiln 1


[kiln]
# Kiln description
# Usually form of {plant} - Kiln {kiln_number}
# [ name: description, type: string, default: Gesotec - Kiln 1 ]
description = Kiln 1

# length unit
# m = meter; f = feet
# [ type: string, valid values: { m, f }, default: m ]
length_unit = m

# Kiln start position
# [ name: kiln_start, type: float, unit: as specified in length_unit, default: 0.0 ]
kiln_start = 0.0

# Kiln end position
# [ name: kiln_end, type: float, unit: as specified in length_unit, default: 100.0 ]
kiln_end = 70.0

# Scanners to be used.
# This defines a list on scanner configuration files
# [name: scanners, type: comma-separated list of scanner config INI files, default: scanner1.ini ]
scanners = scanner1.ini,

[[trigger]]
# Trigger source type
# type=scanner means the trigger is registered on one scanner DaLi-receiver.
# [ name: type, type: string, valid settings: {scanner, tireslip}, default: scanner ]
type = scanner

# Scanner index from which the trigger is used as main kiln trigger
# [ name: scannerID, type: int, value range: [1 to kiln/nscanner], default: 1 ]
scannerID = 1

# Software trigger timeout
# enabled if > 0.0
# [ name: softwareTimeout, type: float, unit: seconds, value range: active: > 0.0,
# inactive> <= 0.0, default: 30.0 ]
softwareTimeout = 30.0

# Minimum trigger interval
# [name: minimum_trigger_interval, type: float, unit: seconds, value range: > 0.0, default: 3.0]
minimum_trigger_interval = 5

# If type == tireslip
# Tireslip channel from which the trigger is used as main kiln trigger
# [ name: tireslip_channel, type: integer, default: 1 ]
tireslip_channel = 3

# If type == tireslip
# Tireslip trigger source IP
# [ name: tireslip_ip, type: str, default: 192.168.10.82 ]
tireslip_ip = 192.168.21.1

# If type == tireslip
# Tireslip multicast group interface binding
# [ name: tireslip_interface, type: str, default: {empty} ]
tireslip_interface = 192.168.10.201

# If type == tireslip
# Tireslip source port
# [ name: tireslip_port, type: integer, default: 50011 ]
tireslip_port = 51001

[[tcem]]
# History  Base Path
# Image History is saved to historyBasePath/IMAGE
# Profile History is saved to historyBasePath/PROFILE
# [ name: historyBasePath, type: directoryName, default: ./tcem_out/history ]
historyBasePath = ../../History/TCEMNET1

# History Image Trigger interval
# Number of kiln syncs at which thermal image are archived.
# Disabled if 0.
# [ name: history_image_sync_interval, type: integer, unit: #kiln syncs, default: 0 ] 	
history_image_sync_interval = 1

# History Image interval
# Interval at which thermal image are archived. Acts as a fallback timeout for 
# History Image Trigger interval.
# [ name: history_image_interval, type: float, unit: seconds, default: 300.0 ]
history_image_interval = 300.0

# History Profile Trigger interval
# Number of kiln syncs at which thermal profiles are archived.
# [ name: history_profile_sync_interval, type: integer, unit: #kiln syncs, default: 0 ]
history_profile_sync_interval = 1

# History Profile interval
# Interval at which thermal profiles are archived.
# [ name: history_profile_interval, type: float, unit: seconds, default: 300.0 ]
history_profile_interval = 300.0

# TCEM Display Temperature Unit
# used for all tcem-related outputs
# [ name: temp_unit, type: string, valid range: {C,K,F}, default: C ]
temp_unit = C


[[text_writer]]
# Is image writer active?
# [ name: active, type: boolean, default: False ]
active = False

# Destination path for text file
# [ name: dest, type: filepath, default: ./image.txt ]
dest = D:/tslip/image.txt

# Add Timestamp to filename
# [ name: filename_timestamp, type: boolean, default: False ]
filename_timestamp = False

# Tireslip Data data, containing tireslip values
# [ name: tireslip_filename, type: filepath, default: Tirestatus.txt ]
tireslip_filename =D:/Gesotec/Tireslip1/tirestatus.txt

# Number of tire sensors to parse, including gear.
num_tire_sensor = 5

# Number of tire sensors to parse, including gear.
horizontal_sensor = 5

# Indent output json file.
# To disable indentation, outcomment this option.
# indent = 4