# This file contains default values for all configuration options.
# Settings written in config.ini will overwrite these options.

[general]
# Application language
# system: use system language if available
# A valid translation needs a *.qm file in folder languages/
# [ name: language, type: string, valid: {"system", "en", "de" }, default: system ]
language = en

# Application instance description, displayed in the SystemTray tooltip
# [ name: description, type: string, default: {empty} ]
description = Kiln 1

# Start CIU-NET Minimized
# [ name: start_minimized, type: boolean, valid: { True, False}, default: True ]
start_minimized = True

# Show scanner timeout messages
# [ name: show_timeouts, type: boolean, valid: { True, False}, default: False ]
show_timeouts = False


# Application window icon
# [ name: icon, type: file path, default: icon/scanner1.png ]
icon = icon/scanner1.png

# Status file, ini format
# [ name: status_file, type: file path, default: ciunet_status.ini ]
status_file = logs/ciunet_status.ini
pups = halloo
huhu = 123

[database]
name = kiln1
host = 127.0.0.1
port = 8086
devicestatus_table = devicestatus

[logging]
# Logging File Base Name
# Existing File will be appended
# [ name: logging_file, type: filename, default: ciunet.log ]
logging_file = ciunet.log
test = hallo
# Global Log Level
# Only log messages with a log level equal or higher
# than the global log level will be logged
# LOG LEVELS: 
# CRITICAL 	50
# ERROR 	40
# WARNING 	30
# INFO 		20
# DEBUG 	10
# [ name: logging_level, type: integer, allowed range: 10 to 50, default: 20 ]
logging_level = 40

[debug]
plotanalogvalues = True
#comment out to deactivate
#plotscanline = True
#plottireslip = True
#plotanalogvalues = True

[kiln]
# Kiln description
# Usually form of {plant} - Kiln {kiln_number}
# [ name: description, type: string, default: Gesotec - Kiln 1 ]
description = Kiln 1

# length unit
# m = meter; f = feet
# [ type: string, valid values: { m, f }, default: m ]
length_unit = m

# Kiln start position
# [ name: kiln_start, type: float, unit: as specified in length_unit, default: 0.0 ]
kiln_start = 0.0

# Kiln end position
# [ name: kiln_end, type: float, unit: as specified in length_unit, default: 100.0 ]
kiln_end = 101.0

# Scanners to be used.
# This defines a list on scanner configuration files
# [name: scanners, type: comma-separated list of scanner config INI files, default: scanner1.ini ]
scanners = scanner1.ini, scanner2.ini
softwareTimeout = 60


[[image]]
# Thermal Image width
# Internal image width
# This value should be larger than the number of interpolated data points, in this case usually 8192 / 3 = 2730 pixels per FoV.
# [ name: target_pixel, type: integer, default: 9000 ]
width = 9000

# Thermal Image height
# Internal image height
# This value should be larger than the number of interpolated data points. For a 20Hz Scanner, 1200 points per minute will be
# generated. Choose this value depending on normal kiln sync or kiln sync software timeout. 
# [ name: target_height, type: integer, default: 1500 ]
height = 1500

# Interpolation method used for horizontal interpolation
# Experimental values: { ‘zero’, ‘slinear’, ‘quadratic’, ‘cubic’ or n } 
# where ‘zero’, ‘slinear’, ‘quadratic’ and ‘cubic’ refer to a spline interpolation of zeroth, first, second or third order) 
# or as an integer specifying the order of the spline interpolator to use.
# [ name: horizontal_interpolation, type: str/int, valid values: { "linear", "nearest" }, default: linear ]
horizontal_interpolation_mode = linear

# Interpolation method used for vertical interpolation
# nearest is much faster than linear interpolation
# [ name: vertical_interpolation, type: str, valid values: { "linear", "nearest" }, default: nearest ]
vertical_interpolation_mode = linear

# Image reset value
# The temperature value used when resetting/blacking out the thermal image
# [ name: image_reset_value, type: float, unit: Kelvin, default: 273.15 ]
image_reset_value = 273.15

# Extrapolate vertically if vertical_interpolation_mode = linear
# [ name: vertical_extrapolate, default: False ]
vertical_extrapolate = False


[[image_writer]]
# Is image writer active?
# [ name: active, type: boolean, default: False ]
active = False

# Destination path for image file
# 16 bit greyscale PNG image
# [ name: dest, type: filepath, default: ./image.png ]
dest = ./image.png

[[text_writer]]
# Is image writer active?
# [ name: active, type: boolean, default: False ]
active = True

# Destination path for text file
# [ name: dest, type: filepath, default: ./image.txt ]
dest = D:/tslip/image.txt

# Add Timestamp to filename
# [ name: filename_timestamp, type: boolean, default: False ]
filename_timestamp = False
#sourec_type{internal /statusfile}
source_type = internal

# Tireslip Data data, containing tireslip values
# [ name: tireslip_filename, type: filepath, default: Tirestatus.txt ]
tireslip_filename = D:/Gesotec/Tireslip1/tirestatus.txt

# Number of tire sensors to parse, including gear.
num_tire_sensor = 5

# Number of tire sensors to parse, including gear.
horizontal_sensor = 5

# Indent output json file.
# To disable indentation, outcomment this option.
# indent = 4

[[[image]]]

# image width reduction factor
# Factor by which intermediate raw image is horizontally aggregated to target_pixel length.
# [ name: image_reduction, type: integer, default: 3 ]
width_reduction = 9

# image height reduction factor
# Factor by which intermediate raw image is vertically aggregated to target_pixel length.
# [ name: image_reduction, type: integer, default: 3 ]
height_reduction = 6



[[nowiny_writer]]
# Special writer for Nowiny-PL XML.

# Is image writer active?
# [ name: active, type: boolean, default: False ]
active = False

# URL destination, eg. http://localhost:80/
# [ name: url_dest, type: http destination, default: off ]
url_dest = http://localhost:80/

# XML log output
# Generated XML content is written to this file for debug/log purposes.
# [ name: xml_filedst, type: filename, default: nowiny_xml_output.txt ]
xml_filedst = logs/nowiny_xml_output.txt

# Request timeout
# [ name: timeout, type: float, unit: seconds, default: 3 ]
timeout = 3.0

[[[image]]]

# image width reduction factor
# Factor by which intermediate raw image is horizontally aggregated to target_pixel length.
# [ name: image_reduction, type: integer, default: 3 ]
width_reduction = 37

# image height reduction factor
# Factor by which intermediate raw image is vertically aggregated to target_pixel length.
# [ name: image_reduction, type: integer, default: 3 ]
height_reduction = 30

[[tireslip]]
aktiv = True

[[[database]]]
type = influx
version = 1.8.3
name = kiln1
measurement = tireslip_raw
host = 127.0.0.1
port = 8086

[[trigger]]
# Trigger source type
# type=scanner means the trigger is registered on one scanner DaLi-receiver.
# [ name: type, type: string, valid settings: {scanner, tireslip, udpmessage,virtualadam}, default: scanner ]
type = udpmessage
adam_channel = 0
# if type = udpmessage
message = Trigger
port = 5168
host = 192.168.1.202
# Scanner index from which the trigger is used as main kiln trigger
# [ name: scannerID, type: int, value range: [1 to kiln/nscanner], default: 1 ]
scannerID = 1

# Software trigger timeout
# enabled if > 0.0
# [ name: softwareTimeout, type: float, unit: seconds, value range: active: > 0.0,
# inactive> <= 0.0, default: 60.0 ]
softwareTimeout = 30.0

# Minimum trigger interval
# [name: minimum_trigger_interval, type: float, unit: seconds, value range: > 0.0, default: 3.0]
minimum_trigger_interval = 5.0

# If type == tireslip
# Tireslip channel from which the trigger is used as main kiln trigger
# [ name: tireslip_channel, type: integer, default: 1 ]
tireslip_channel = 3

# If type == tireslip
# Tireslip multicast group
# [ name: tireslip_group, type: str, default: 239.1.1.1 ]
tireslip_group = 239.1.1.1

# If type == tireslip
# Tireslip trigger source IP
# [ name: tireslip_ip, type: str, default: 192.168.10.82 ]
tireslip_ip = 192.168.21.1


# If type == tireslip
# Tireslip multicast group interface binding
# [ name: tireslip_interface, type: str, default: {empty} ]
tireslip_interface = 192.168.10.201


# If type == tireslip
# Tireslip source port
# [ name: tireslip_port, type: integer, default: 50011 ]
tireslip_port = 51001
ext_port = 1025
local_port = 5168


[[tcem]]
# TCEM.NET base path
# [ name: tcempath, type: directoryName, default: ../ ]
#tcempath = ../
tcempath = ../

# Use locale for writing text files, namely:
# serial file
# [ name: use_locale, type: boolean, default: False ]
use_locale = False

# index for ciuN output directory
# [ name: ciu_index, type: integer, default: 1 ]
ciu_index = 1

# History  Base Path
# Image History is saved to historyBasePath/IMAGE
# Profile History is saved to historyBasePath/PROFILE
# [ name: historyBasePath, type: directoryName, default: ./tcem_out/history ]
historyBasePath = ../../History/TCEMNET1

# History Image Trigger interval
# Number of kiln syncs at which thermal image are archived.
# Disabled if 0.
# [ name: history_image_sync_interval, type: integer, unit: #kiln syncs, default: 0 ]
history_image_sync_interval = 0

# History Image interval
# Interval at which thermal image are archived. Acts as a fallback timeout for 
# History Image Trigger interval.
# [ name: history_image_interval, type: float, unit: seconds, default: 300.0 ]
history_image_interval = 600.0

# History Profile Trigger interval
# Number of kiln syncs at which thermal profiles are archived.
# [ name: history_profile_sync_interval, type: integer, unit: #kiln syncs, default: 0 ]
history_profile_sync_interval = 0

# History Profile interval
# Interval at which thermal profiles are archived.
# [ name: history_profile_interval, type: float, unit: seconds, default: 300.0 ]
history_profile_interval = 300.0

# TCEM image refresh/write interval
# how often image for TCEM is updated
# [ name: refreshInterval, type: float, unit: seconds, valid values: >= 1.0 for
# timerdepended update, <=0:update on trigger, default: -1 ]
refreshInterval = -1.0

# TCEM Display Temperature Unit
# used for all tcem-related outputs
# [ name: temp_unit, type: string, valid range: {C,K,F}, default: C ]
temp_unit = C

[[[server]]]
#comment server out to disable
tcemserver = aktiv
port = 55555
#webserver=aktiv							  

[[[image]]]
# TCEM image bits per pixel
# [ name: bits_per_pixel, type: int, valid range: 8-16, default: 16 ]
bits_per_pixel = 16

# TCEM image lower temperature bound
# [ name: tscale_tlow, type: float, unit: °Celsius, default: -273.15 ]
tscale_tlow = -273.15

# TCEM image upper temperature bound
# [ name: tscale_tup, type: float, unit: °Celsius, default: 2048.0 ]
tscale_tup = 2048.0

# image width reduction factor
# Factor by which intermediate raw image is horizontally aggregated to target_pixel length.
# Adjusted width should roughly match your horizontal display resolution.
# [ name: image_reduction, type: integer, default: 3 ]
width_reduction = 3

# image height reduction factor
# Factor by which intermediate raw image is vertically aggregated to target_pixel length.
# Adjusted height should roughly match your vertical display resolution.
# [ name: image_reduction, type: integer, default: 3 ]
height_reduction = 3

# TCEM image vertical scale upper position
# [ name: vscale_low, type: float, default: 0.0 ]
vscale_low = 0.0

# TCEM image vertical scale lower position
# [ name: vscale_high, type: float, default: 360.0 ]
vscale_high = 360.0

# TCEM image vertical unit
# d is interpreted as degree by TCEM
# [ name: vertical_length_unit, valid range: {d, m, f}, default: d ]
vertical_length_unit = d


[[[windows]]]
# Parses TCEM Image every time it is written to TCEM for window boundaries

# Window alarm output file
# [ name: outFile, type: fileName, default: ../ciu1/Window/WINDOW.1 ]
outFile = ../ciu1/Window/WINDOW.1

# Window alarm CSV output file
# [ name: outFileCSV, type: fileName, default: ./Windows.csv ]
outFileINI = ./Windows.ini

# Window alarm CSV output file write interval
# [ name: outFileCSV_interval, type: float, unit: seconds, default: 5.0 ]
outFileINI_interval = 5.0

# TCEM window config file
# [ name: configFile, type: fileName, default: ../ciu1/window1.ini ]
configFile = ../ciu1/window1.ini

# How often TCEM window config file is re-parsed
# [ name: configParseInterval, type: float, unit: seconds, valid range: > 0.0 ]
configParseInterval = 3.0
[tireslip]

timeout = 500
filename = Tirecr.1
opcFilename = Tirecr.opc


[[stability]]
interval = 900
minRPM = 0.2
maxRPM = 10
sigmaMax = 0.2
aMax = 0.01
aMin = 0.01
mininterval = 0.5
[[gear]]
channel = 7
r = 2098
average_interval = 300
average_rotations = 10
rising = True
falling = True
x = 45
mininterval = 0.5
minRPM = 0.1
maxRPM = 100
sigmaMax = 100
show = True

[[tire0]]
type = single
channel = 0
x = 59.7
r = 2098
average_interval = 900
average_rotations = 10
rising = True
falling = True
minSlip = -20
maxSlip = 500
mininterval = 0.5
show = True
minAlarmSlip = 0
miaxAlarmSlip = 100.0
maxAlarmSlip = 100.0
[[tire3]]
channel = 3
x = 4
r = 2098
average_interval = 900
average_rotations = 10
rising = True
falling = True
minSlip = -20
maxSlip = 500
mininterval = 0.5
minAlarmSlip = 0
maxAlarmSlip = 500.0
[[tire2]]
channel = 2
x = 21.0
r = 2098
average_interval = 900
average_rotations = 10
rising = True
falling = True
minSlip = -20
maxSlip = 500
mininterval = 0.5
minAlarmSlip = 0
maxAlarmSlip = 500.0
[[tire1]]
channel = 1
x = 40.0
r = 2098
average_interval = 900
average_rotations = 10
rising = True
falling = True
minSlip = -20
maxSlip = 500
mininterval = 0.5
minAlarmSlip = 0
maxAlarmSlip = 500.0
