[network]
#local only
ip=127.0.0.1
#multicast
#ip=239.1.1.1

[line]
npixels=8192
video=2730
u0=204


[source]
# 0: full tcem image (360deg)
# 1: tcem image, only video signal
# 2: video from png, not implemented
# 3: test pattern
type=3
source_dir=C:\Projekte\arbeit\ggrdaq\data\360
scanner_frq=20
[trigger]
interval=5
deviation=1
host=127.0.0.1
port=9998


[simulation_0]
#0:vertikaler Verlauf
#1:horizontaler Verlauf
#2:chessboard
pattern=2
chessboard_h_frq=200
chessboard_v_frq=10
value_0=300
value_1=400
nlines=100
[simulation_1]
#0:vertikaler Verlauf
#1:horizontaler Verlauf
#2:chessboard
pattern=2
chessboard_h_frq=200
chessboard_v_frq=10
value_0=400
value_1=300
nlines=100

[extra_data_0]
angle_start=129
angle_stop=138
low_value=0
high_value=633

[extra_data_1]
#interne temp
angle_start=143
angle_stop=153
low_value=0
high_value=1795
[extra_data_2]
#LowRef
angle_start=158
angle_stop=168
low_value=0
high_value=201
[extra_data_3]
#HighRef
angle_start=221
angle_stop=226
low_value=0
high_value=1829
[extra_data_4]
#Body
angle_start=290
angle_stop=300
low_value=0
high_value=400
[extra_data_5]
#Body
angle_start=308
angle_stop=318
low_value=0
high_value=202
[extra_data_6]
#Body
angle_start=322
angle_stop=333
low_value=0
high_value=202
[extra_data_7]
#Body
angle_start=336
angle_stop=347
low_value=0
high_value=201

[extra_data_8]
#Body
angle_start=180
angle_stop=190
low_value=0
high_value=208