[logging]
# Logging File Base Name
# [ type: filename, existing file will be appended ]
log_file = device_status.log

# Global Log Level Threshold. Only log messages with a log level equal or higher
# than the global log level will be loged and displayed
# LOG LEVELS:
# CRITICAL 50
# ERROR 	40
# WARNING 	30
# INFO 	20
# DEBUG 	10
# [ type: integer, allowed range: 10 to 50 ]
logging_level = 20

[StatusViewer]
listenPort=51000
multicastGroup=239.1.1.1
sourceFilter=

# Network Interface to which receiver UDP socket is bound to (PC Notwork port)
# Specification is a valid IP interface Address, IPv4 or IPv6 following RFC5952 specification
# If not specified, the socket will not be bound to a specific interface
# [ type: string ]
#interface=192.168.6.201

status_file = device_status.json
[interface]
# DaLi-Net IP-address
#interface=192.168.12.11
