[general]

description = string()
language = string()
start_minimized = boolean()
show_timeouts = boolean()
icon = string()
status_file = string()

[logging]
logging_file = string()
logging_level = integer()

[kiln]
description = string()
length_unit = option("m", "f")
kiln_start = float()
kiln_end = float()
scanners = force_list()

[[image]]
width=integer()
height=integer()
horizontal_interpolation_mode = option("linear", "nearest", ‘zero’, ‘slinear’, ‘quadratic’,‘cubic’)
vertical_interpolation_mode = option("linear", "nearest")
image_reset_value = float(min=0)
vertical_extrapolate = boolean()

[[image_writer]]
active = boolean()
dest = string()

[[text_writer]]
active = boolean()
dest = string()
filename_timestamp = boolean()
tireslip_filename = string()

[[[image]]]
width_reduction = integer(min=1)
height_reduction = integer(min=1)

[[nowiny_writer]]
active = boolean()
url_dest = string()
xml_filedst = string()
timeout = float(max=10)

[[[image]]]
width_reduction = integer(min=1)
height_reduction = integer(min=1)

[[trigger]]
type = option("scanner", "tireslip")
scannerID = integer()
softwareTimeout = float()
minimum_trigger_interval = float(min=0)
tireslip_channel = integer()
tireslip_group = ip_addr()
tireslip_ip = ip_addr()
tireslip_interface = string()
tireslip_port = integer(min=0, max=65535)

[[tcem]]
tcempath = string()
use_locale = boolean()
ciu_index = integer()
historyBasePath = string()
history_image_sync_interval = integer(min=0)
history_image_interval = float()
history_profile_sync_interval = integer(min=0)
history_profile_interval = float()
refreshInterval = float()
temp_unit = option("C", "K", "F")

[[[image]]]
bits_per_pixel = integer(min=8,max=16)
tscale_tlow = float()
tscale_tup = float()
width_reduction = integer(min=1)
height_reduction = integer(min=1)
vscale_low = float()
vscale_high = float()
vertical_length_unit = option("d", "m", "f")

[[[windows]]]
# Window alarm output file
# [ name: outFile, type: fileName, default: ../ciu1/Window/WINDOW.1 ]
outFile = string()

# Window alarm CSV output file
# [ name: outFileCSV, type: fileName, default: ./Windows.csv ]
outFileINI = string()

# Window alarm CSV output file write interval
# [ name: outFileCSV_interval, type: float, unit: seconds, default: 5.0 ]
outFileINI_interval = float(min=0.1)

# TCEM window config file
# [ name: configFile, type: fileName, default: ../ciu1/window1.ini ]
configFile = string()

# How often TCEM window config file is re-parsed
# [ name: configParseInterval, type: float, unit: seconds, valid range: > 0.0 ]
configParseInterval = float(min=0.1)
