import os
import logging
from collections import OrderedDict
import datetime
from xml.dom.minidom import parseString

from Qt import QtCore
import numpy
import requests
import pyxb

from python_util import util
# This file is auto-generated by build_scheme.bat and contains the XML structure for pyxb, which also validates the 
# given XML Schema when creating the XML output.
from . import nowiny_writer_defs as nw
from daq_net.daq import Temperature
from ciunet.processing.ComposedImageView import ComposedImageViewer


STRICT_WIDTH = 240
STRICT_HEIGHT = 64


class NowinyXMLWriter(QtCore.QObject):
    def __init__(self, composed_image, config, kiln, parent):
        super().__init__(parent)
        self.logger = logging.getLogger(self.__class__.__name__)
        self.active = config.get("active", False)
        if not self.active:
            return
        self.kiln = kiln
        self.xml_filedst = os.path.abspath(config["xml_filedst"])

        self.composed_image = composed_image
        self.image_viewer = ComposedImageViewer(config["image"], composed_image, self)
        width = self.image_viewer.width
        if STRICT_WIDTH:
            if width != STRICT_WIDTH:
                raise ValueError("Nowiny requires strict image width of {}, not {}.".format(STRICT_WIDTH, width))
        height = self.image_viewer.height
        if STRICT_HEIGHT:
            if height != STRICT_HEIGHT:
                raise ValueError("Nowiny requires strict image height of {}, not {}.".format(STRICT_HEIGHT, height))

        self.timeout = float(config["timeout"])
        try:
            self.kilnID = int(self.kiln.description)
        except ValueError as e:
            raise ValueError("Cannot create Nowiny XML writer with non-integral kiln description") from e
        self.filename_timestamp = util.str2bool((config.get("filename_timestamp", "false")))
        self.url_dest = config.get("url_dest", None)

    def build_data(self):
        try:
            temp_meas = nw.TempMeas()
            temp_meas.IdKiln = int(self.kiln.description)

            now = datetime.datetime.utcnow().replace(microsecond=0)
            # https://www.w3schools.com/xml/schema_dtypes_date.asp
            temp_meas.Date = "{:%Y-%m-%dT%H:%M:%SZ}".format(now)

            temp_meas.Sections = pyxb.BIND()
            temp_meas.Sections.Section = []
            # list(list) of temperatures in °C as integers
            image_data = Temperature.kelvinToCelsius(self.image_viewer.image).astype(numpy.int).transpose().tolist()
            num_sections = len(image_data)
            for i in range(num_sections):
                # Position in the middle of the section in millimeters
                pos_middle = int(self.kiln.kiln_start + (self.kiln.kiln_end - self.kiln.kiln_start) *
                                 (i + 0.5) / num_sections * 1000.0)
                section = pyxb.BIND(Position=pos_middle, Temps=pyxb.BIND(temp=image_data[i]))
                temp_meas.Sections.Section.append(section)
            return temp_meas
        except Exception as e:
            raise RuntimeError("Could not build XML data.") from e

    @util.noexcept
    def log_xml(self, xml_output):
        """Write generated xml to log file for debug purposes"""
        self.logger.debug("Logging output to {}.".format(self.xml_filedst))
        dom = parseString(xml_output)
        with open(self.xml_filedst, "w") as f:
            f.write(dom.toprettyxml())

    def post_data(self, xml_output):
        """Post XML data to URL"""
        if not self.url_dest:
            return
        r = requests.post(self.url_dest, xml_output, timeout=self.timeout)
        r.raise_for_status()

    def save_image(self):
        """Build and save/post Nowiny XML image"""
        if not self.active:
            return
        self.logger.info("Creating output.")
        start_xml_build = datetime.datetime.now()
        temp_meas = self.build_data()
        self.logger.debug("Building XML took {}.".format(datetime.datetime.now() - start_xml_build))
        start_xml_output = datetime.datetime.now()
        xml_output = temp_meas.toxml()
        self.logger.debug("Creating XMLstring took {}.".format(datetime.datetime.now() - start_xml_output))
        self.log_xml(xml_output)
        self.post_data(xml_output)

    @QtCore.Slot()
    @util.noexcept
    def registerTrigger(self):
        try:
            self.save_image()
        except Exception as e:
            self.logger.error("Could not save image: {}".format(e))
            self.logger.debug("Could not save image", exc_info=True)
